apiVersion: v1
kind: Service
metadata:
  name: devops-fastapi
  namespace: production
  labels:
    app: devops-fastapi
    environment: production
spec:
  type: NodePort
  selector:
    app: devops-fastapi
    environment: production
  ports:
  - name: http
    protocol: TCP
    port: 8000        # Internal cluster port
    targetPort: 8000  # Container port
    nodePort: 30000   # External port (will map to 8000)
  sessionAffinity: None
